name: Metrics
on:
  schedule: 
    - cron: "0 0 * * *"       # Ejecuta diariamente
  push:
    branches: ["main", "master"]

jobs:
  render-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write         # Permite actualizar archivos en el repo
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/images/metrics.plugin.isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          # Opcional: duración completa del año
          # plugin_isocalendar_duration: full-year
